// ═══════════════════════════════════════
//  DIAGNOSIS PAGE — Translations & Logic
// ═══════════════════════════════════════

// Extend global translations
translations.en = Object.assign(translations.en, {
    "diag_badge": "Smart Analysis",
    "diag_title": "New AI Diagnosis",
    "diag_subtitle": "Upload your medical scans or reports for an instant, preliminary AI analysis powered by deep learning.",
    "diag_type_label": "Select Examination Type",
    "diag_type_placeholder": "Choose an option...",
    "type_xray": "Bone Fracture (X-Ray)",
    "type_skin": "Dermatology (Skin Image)",
    "type_ecg": "Pneumonia (Chest X-Ray)",
    "type_blood": "Brain Tumors (MRI)",
    "type_pdf": "General Medical Report (PDF)",
    "diag_info_text": "Our AI models are specifically trained for these types of medical data.",
    "diag_upload_label": "Upload File",
    "drag_drop": "Drag and drop file here",
    "or_browse": "or click to browse from your device",
    "btn_browse": "Browse Files",
    "btn_analyze": "Analyze with AI",
    "ai_analyzing": "AI is analyzing your data...",
    "ai_analyzing_sub": "Detecting anomalies and patterns using our neural network.",
    "diag_result_title": "Analysis Results",
    "btn_book_specialist": "Book Consultation",
    "recommended": "Recommended Action",
    "detection_success": "Detection Successful",
    "upload_error": "Please upload a file first.",
    "type_error": "Please select examination type.",
    "selected_exam": "Selected Examination",
    "btn_change": "Change Selection",
    "btn_new_scan": "Perform Another Scan",
    "create_pdf_report": "General Medical Report (PDF)",
    "report_summary": "Medical Report Summary",
    "findings_label": "Findings & Diagnosis",
    "specialist_label": "Recommended Specialist",
    "confidence_label": "Confidence Level",
    "hw_confidence": "Confidence Score",
    "suggested_docs_title": "Recommended Specialists",
    "report_hospital": "Smart Care 360 Hospital",
    "report_dept": "Advanced Medical Diagnostics Dept.",
    "report_title": "Medical Report",
    "report_date": "Date:",
    "report_ref": "Ref No:",
    "report_patient_details": "Patient Details",
    "report_name": "Name:",
    "report_email": "Email:",
    "report_age": "Age:",
    "report_gender": "Gender:",
    "report_scan_details": "Scan Details",
    "report_exam": "Examination:",
    "report_processing": "Processing:",
    "report_processing_val": "AI Deep Learning Analysis",
    "report_findings": "AI Diagnostic Findings",
    "report_detection": "Detection Result",
    "report_confidence": "AI Confidence",
    "report_recommendation": "Recommended Action",
    "report_consultant": "Consultant / Doctor",
    "report_ai_verified": "AI System Verified",
    "report_disclaimer": "This report was automatically generated by Smart Care 360 System. It serves as preliminary diagnostic support and must be reviewed by a certified medical professional.",
    "report_detailed_title": "Detailed Medical Report",
    "report_affected_bone": "Affected Bone",
    "report_fracture_type": "Fracture Type",
    "report_severity": "Severity",
    "report_tech_desc": "Technical Medical Description",
    "report_treatment": "Suggested Treatment Plan & Recommendations",
    "report_heatmap": "Location of Injury Heatmap Visualization (Grad-CAM)",
    "report_page": "Page",
    "report_phone": "Phone",
    "report_brand": "Smart Care 360",
    "report_system_sig": "AI Diagnostic System"
});

translations.ar = Object.assign(translations.ar, {
    "diag_badge": "تحليل ذكي",
    "diag_title": "تشخيص جديد بالذكاء الاصطناعي",
    "diag_subtitle": "قم بتحميل الأشعة أو التقارير الطبية للحصول على تحليل فوري ومبدئي مدعوم بالتعلم العميق.",
    "diag_type_label": "اختر نوع الفحص",
    "diag_type_placeholder": "اختر خياراً...",
    "type_xray": "كسور العظام (أشعة سينية)",
    "type_skin": "أمراض جلدية (صورة جلدية)",
    "type_ecg": "الالتهاب الرئوي (أشعة الصدر)",
    "type_blood": "أورام المخ (رنين مغناطيسي)",
    "type_pdf": "تقرير طبي عام (PDF)",
    "diag_info_text": "نماذج الذكاء الاصطناعي مخصصة لهذه الأنواع فقط من البيانات الطبية.",
    "diag_upload_label": "تحميل الملف",
    "drag_drop": "اسحب وأفلت الملف هنا",
    "or_browse": "أو انقر للتصفح من جهازك",
    "btn_browse": "تصفح الملفات",
    "btn_analyze": "ابدأ التحليل",
    "ai_analyzing": "جاري تحليل البيانات...",
    "ai_analyzing_sub": "الكشف عن الأنماط والحالات الشاذة باستخدام شبكتنا العصبية.",
    "diag_result_title": "نتائج التحليل",
    "btn_book_specialist": "حجز موعد استشارة",
    "recommended": "الإجراء الموصى به",
    "detection_success": "تم التحليل بنجاح",
    "upload_error": "يرجى تحميل ملف أولاً.",
    "type_error": "يرجى اختيار نوع الفحص.",
    "selected_exam": "الفحص المحدد",
    "btn_change": "تغيير الفحص",
    "btn_new_scan": "قم بإجراء فحص جديد",
    "create_pdf_report": "تقرير طبي عام (PDF)",
    "report_summary": "ملخص التقرير الطبي",
    "findings_label": "النتائج والتشخيص",
    "specialist_label": "الطبيب المختص المقترح",
    "confidence_label": "نسبة التأكد",
    "hw_confidence": "نسبة الثقة",
    "suggested_docs_title": "الأطباء المختصون المقترحون",
    "report_hospital": "مستشفى سمارت كير 360",
    "report_dept": "قسم التشخيص الطبي المتقدم",
    "report_title": "تقرير طبي",
    "report_date": "التاريخ:",
    "report_ref": "رقم المرجع:",
    "report_patient_details": "بيانات المريض",
    "report_name": "الاسم:",
    "report_email": "البريد:",
    "report_age": "العمر:",
    "report_gender": "النوع:",
    "report_scan_details": "بيانات الفحص",
    "report_exam": "الفحص:",
    "report_processing": "المعالجة:",
    "report_processing_val": "تحليل بالذكاء الاصطناعي والتعلم العميق",
    "report_findings": "نتائج تشخيص الذكاء الاصطناعي",
    "report_detection": "نتيجة الكشف",
    "report_confidence": "نسبة الثقة",
    "report_recommendation": "الإجراء الموصى به",
    "report_consultant": "الطبيب المعالج",
    "report_ai_verified": "معتمد من النظام",
    "report_disclaimer": "تم إنشاء هذا التقرير تلقائياً بواسطة نظام سمارت كير 360. وهو بمثابة دعم تشخيصي مبدئي ويجب مراجعته من قبل طبيب مختص.",
    "report_detailed_title": "التقرير الطبي المفصل",
    "report_affected_bone": "العظمة المتأثرة",
    "report_fracture_type": "نوع الكسر",
    "report_severity": "درجة الخطورة",
    "report_tech_desc": "الوصف الطبي الفني",
    "report_treatment": "الخطة العلاجية والتوصيات المقترحة",
    "report_heatmap": "خريطة كشف موقع الإصابة والتظليل الحراري (Grad-CAM)",
    "report_page": "صفحة",
    "report_phone": "الهاتف",
    "report_brand": "سمارت كير 360",
    "report_system_sig": "منظومة التشخيص الذكية"
});

// Intersection Observer for reveal animations
const revealObserver = new IntersectionObserver((entries) => {
    entries.forEach(entry => {
        if (entry.isIntersecting) {
            entry.target.classList.add('visible');
        }
    });
}, { threshold: 0.1 });

function initReveals() {
    document.querySelectorAll('.reveal-up, .reveal-left, .reveal-right').forEach(el => {
        revealObserver.observe(el);
    });
}

// ═══════════════════════
//  Interactive Logic
// ═══════════════════════

const dropzone = document.getElementById('dropzone');
const fileInput = document.getElementById('fileInput');
const previewArea = document.getElementById('previewArea');
const previewMedia = document.getElementById('previewMedia');
const fileNameDisplay = document.getElementById('fileNameDisplay');
let selectedFile = null;

// File Handling
['dragenter', 'dragover', 'dragleave', 'drop'].forEach(e => {
    dropzone.addEventListener(e, (evt) => {
        evt.preventDefault();
        evt.stopPropagation();
    });
});

dropzone.addEventListener('dragover', () => dropzone.classList.add('dragover'));
dropzone.addEventListener('dragleave', () => dropzone.classList.remove('dragover'));
dropzone.addEventListener('drop', (e) => {
    dropzone.classList.remove('dragover');
    handleFiles(e.dataTransfer.files);
});

fileInput.addEventListener('change', (e) => handleFiles(e.target.files));

function handleFiles(files) {
    if (files.length > 0) {
        selectedFile = files[0];
        displayPreview(selectedFile);
        
        // Auto-start if a scan type is already selected
        if (document.getElementById('scanType').value) {
            setTimeout(() => document.getElementById('analyzeBtn').click(), 300);
        }
    }
}

function displayPreview(file) {
    fileNameDisplay.textContent = file.name;
    previewArea.classList.remove('d-none');
    previewMedia.innerHTML = '';
    
    if (file.type.startsWith('image/')) {
        const img = document.createElement('img');
        const reader = new FileReader();
        reader.onload = (e) => {
            img.src = e.target.result;
            window.lastUploadedFileDataUrl = e.target.result;
        };
        reader.readAsDataURL(file);
        previewMedia.appendChild(img);
    } else if (file.type === 'application/pdf') {
        const iframe = document.createElement('iframe');
        iframe.src = URL.createObjectURL(file);
        previewMedia.appendChild(iframe);
        window.lastUploadedFileDataUrl = null;
    }
}

window.clearPreview = function() {
    selectedFile = null;
    fileInput.value = '';
    window.lastUploadedFileDataUrl = null;
    previewArea.classList.add('d-none');
    document.getElementById('resultArea').classList.add('d-none');
};

// ═══════════════════════
//  Analysis Logic
// ═══════════════════════

document.getElementById('diagnosisForm').addEventListener('submit', async (e) => {
    e.preventDefault();
    
    const scanType = document.getElementById('scanType').value;
    const lang = localStorage.getItem('mediai_lang') || 'en';

    if (!scanType) return showAlert(translations[lang].type_error, 'warning');
    if (!selectedFile) return showAlert(translations[lang].upload_error, 'warning');

    const analyzeBtn = document.getElementById('analyzeBtn');
    const analysisLoader = document.getElementById('analysisLoader');
    const progress = document.getElementById('analysisProgress');
    const resultArea = document.getElementById('resultArea');

    // Auth Check on Action
    const role = localStorage.getItem('mediai_auth_role');
    if (!role) {
        window.location.href = '../login/login.html?redirect=../diagnosis/diagnosis.html';
        return;
    }

    // UI Loading State
    analyzeBtn.classList.add('d-none');
    analysisLoader.classList.remove('d-none');
    resultArea.classList.add('d-none');

    // Progress bar simulation
    let width = 0;
    const interval = setInterval(() => {
        if (width >= 100) clearInterval(interval);
        else {
            width += (Math.random() * 15);
            if (width > 100) width = 100;
            progress.style.width = width + '%';
        }
    }, 400);

    try {
        let result;

        if (scanType === 'xray_bone') {
            // === DIRECT call to Hugging Face Space for X-Ray Bone Fracture ===
            console.log('[AI] Sending directly to Hugging Face Space (Bilingual requests)...');
            const hfFormDataAr = new FormData();
            hfFormDataAr.append('file', selectedFile);
            hfFormDataAr.append('lang', 'ar');

            const hfFormDataEn = new FormData();
            hfFormDataEn.append('file', selectedFile);
            hfFormDataEn.append('lang', 'en');

            const [responseAr, responseEn] = await Promise.all([
                fetch('https://hazemfarag-bone-fraction.hf.space/predict', { method: 'POST', body: hfFormDataAr }),
                fetch('https://hazemfarag-bone-fraction.hf.space/predict', { method: 'POST', body: hfFormDataEn })
            ]);

            if (!responseAr.ok || !responseEn.ok) {
                const failedStatus = !responseAr.ok ? responseAr.status : responseEn.status;
                throw new Error(lang === 'ar' 
                    ? `فشل الاتصال بخدمة الذكاء الاصطناعي (HTTP ${failedStatus})` 
                    : `AI service connection failed (HTTP ${failedStatus})`);
            }

            const [hfDataAr, hfDataEn] = await Promise.all([
                responseAr.json(),
                responseEn.json()
            ]);

            console.log('[AI] HF Space responses received:', hfDataAr.prediction, hfDataEn.prediction);

            if (hfDataAr.success === false || hfDataEn.success === false) {
                const rawError = hfDataAr.error || hfDataEn.error || '';
                const errorMsg = rawError.toLowerCase().includes('cannot read')
                    ? (lang === 'ar'
                        ? 'تعذر تحليل الصورة المرفوعة. هذا الموديل لا يدعم تحليل هذا النوع من الصور. يرجى رفع صورة أشعة سينية (X-Ray) واضحة للعظام.'
                        : 'Unable to analyze the uploaded image. This model does not support this image type. Please upload a clear bone X-ray (X-Ray) image.')
                    : rawError || (lang === 'ar'
                        ? 'الصورة المرفوعة ليست صورة أشعة عظام صالحة. يرجى رفع صورة أشعة سينية (X-Ray) واضحة للعظام.'
                        : 'The uploaded image is not a valid bone X-ray. Please upload a clear bone X-ray.');
                throw new Error(errorMsg);
            }

            const predTextAr = hfDataAr.prediction || '';
            const predTextEn = hfDataEn.prediction || '';

            let confidencePercent = hfDataEn.confidence || hfDataAr.confidence || 90;
            if (typeof confidencePercent === 'number') {
                confidencePercent = confidencePercent.toFixed(2);
            }

            const isFracturedAr = predTextAr.includes('مكسور') || predTextAr.includes('كسر') || predTextAr.includes('??????');
            const isFracturedEn = predTextEn.toLowerCase().includes('fracture') || predTextEn.toLowerCase().includes('fractured');

            const repAr = hfDataAr.report_data || {};
            const repEn = hfDataEn.report_data || {};

            // Build bilingual aiResult for language-aware rendering
            const aiResultObj = {
                _isBilingual: true,
                Confidence: confidencePercent + '%',

                // Arabic fields
                DiagnosisAr: predTextAr,
                RecommendationsAr: isFracturedAr
                    ? 'يرجى مراجعة طبيب عظام فوراً لعمل جبيرة أو تدخل جراحي.'
                    : 'لا توجد علامات واضحة لكسر، يرجى الراحة والمتابعة في حال زاد الألم.',
                BoneNameAr: repAr.bone_name || '',
                SeverityAr: repAr.severity || '',
                MedicalReportAr: repAr.report || '',
                TreatmentPlanAr: repAr.treatment_plan || '',

                // English fields
                DiagnosisEn: predTextEn,
                RecommendationsEn: isFracturedEn
                    ? 'Please consult an orthopedic specialist immediately.'
                    : 'No clear signs of fracture. Rest and follow up if pain persists.',
                BoneNameEn: repEn.bone_name || '',
                SeverityEn: repEn.severity || '',
                MedicalReportEn: repEn.report || '',
                TreatmentPlanEn: repEn.treatment_plan || '',

                // Standard fallback fields (based on active lang at scan time)
                Diagnosis: lang === 'ar' ? predTextAr : predTextEn,
                Recommendations: lang === 'ar'
                    ? (isFracturedAr ? 'يرجى مراجعة طبيب عظام فوراً لعمل جبيرة أو تدخل جراحي.' : 'لا توجد علامات واضحة لكسر، يرجى الراحة والمتابعة في حال زاد الألم.')
                    : (isFracturedEn ? 'Please consult an orthopedic specialist immediately.' : 'No clear signs of fracture. Rest and follow up if pain persists.'),
                BoneName: lang === 'ar' ? (repAr.bone_name || '') : (repEn.bone_name || ''),
                Severity: lang === 'ar' ? (repAr.severity || '') : (repEn.severity || ''),
                MedicalReport: lang === 'ar' ? (repAr.report || '') : (repEn.report || ''),
                TreatmentPlan: lang === 'ar' ? (repAr.treatment_plan || '') : (repEn.treatment_plan || ''),
                Heatmap: hfDataEn.heatmap || hfDataAr.heatmap || '',
                _lang: lang
            };

            result = {
                scanType: scanType,
                fileName: selectedFile.name,
                filePath: '',
                aiResult: JSON.stringify(aiResultObj),
                createdAt: new Date().toISOString()
            };

            // Also save to backend database (fire-and-forget, don't block the UI)
            try {
                const saveFormData = new FormData();
                saveFormData.append('file', selectedFile);
                saveFormData.append('scanType', scanType);
                saveFormData.append('Lang', lang);
                Api.diagnosis.analyze(saveFormData).catch(e => console.warn('[AI] Backend save warning:', e.message));
            } catch(saveErr) {
                console.warn('[AI] Backend save skipped:', saveErr.message);
            }

        } else if (scanType === 'ecg_heart') {
            // === DIRECT call to Hugging Face Space for Pneumonia Chest X-Ray ===
            console.log('[AI] Sending directly to Pneumonia HF Space (Bilingual requests)...');
            const hfFormDataAr = new FormData();
            hfFormDataAr.append('file', selectedFile);
            hfFormDataAr.append('lang', 'ar');

            const hfFormDataEn = new FormData();
            hfFormDataEn.append('file', selectedFile);
            hfFormDataEn.append('lang', 'en');

            const [responseAr, responseEn] = await Promise.all([
                fetch('https://hazemfarag-pneumonia-diagnosis-ai.hf.space/predict/chest-xray', { method: 'POST', body: hfFormDataAr }),
                fetch('https://hazemfarag-pneumonia-diagnosis-ai.hf.space/predict/chest-xray', { method: 'POST', body: hfFormDataEn })
            ]);

            if (!responseAr.ok || !responseEn.ok) {
                const failedStatus = !responseAr.ok ? responseAr.status : responseEn.status;
                throw new Error(lang === 'ar' 
                    ? `فشل الاتصال بخدمة الذكاء الاصطناعي (HTTP ${failedStatus})` 
                    : `AI service connection failed (HTTP ${failedStatus})`);
            }

            const [hfDataAr, hfDataEn] = await Promise.all([
                responseAr.json(),
                responseEn.json()
            ]);

            console.log('[AI] Pneumonia HF Space responses received:', hfDataAr.prediction, hfDataEn.prediction);

            if (hfDataAr.success === false || hfDataEn.success === false) {
                const rawError = hfDataAr.error || hfDataEn.error || '';
                const errorMsg = rawError.toLowerCase().includes('cannot read')
                    ? (lang === 'ar'
                        ? 'تعذر تحليل الصورة المرفوعة. هذا الموديل لا يدعم تحليل هذا النوع من الصور. يرجى رفع صورة أشعة سينية (X-Ray) واضحة للصدر.'
                        : 'Unable to analyze the uploaded image. This model does not support this image type. Please upload a clear chest X-ray (X-Ray) image.')
                    : rawError || (lang === 'ar'
                        ? 'الصورة المرفوعة ليست صورة أشعة صدر صالحة. يرجى رفع صورة أشعة سينية (X-Ray) واضحة للصدر.'
                        : 'The uploaded image is not a valid chest X-ray. Please upload a clear chest X-ray.');
                throw new Error(errorMsg);
            }

            const predTextAr = hfDataAr.prediction || '';
            const predTextEn = hfDataEn.prediction || '';

            let confidencePercent = hfDataEn.confidence || hfDataAr.confidence || 90;
            if (typeof confidencePercent === 'number') {
                confidencePercent = confidencePercent.toFixed(2);
            }

            const isAbnormalAr = predTextAr.includes('التهاب') || predTextAr.includes('مريض') || predTextAr.includes('??????');
            const isAbnormalEn = predTextEn.toLowerCase().includes('pneumonia') || predTextEn.toLowerCase().includes('abnormal') || predTextEn.toLowerCase().includes('warning');

            const repAr = hfDataAr.report_data || {};
            const repEn = hfDataEn.report_data || {};

            // Build bilingual aiResult for language-aware rendering
            const aiResultObj = {
                _isBilingual: true,
                Confidence: confidencePercent + '%',

                // Arabic fields
                DiagnosisAr: predTextAr,
                RecommendationsAr: isAbnormalAr
                    ? 'يرجى مراجعة طبيب أمراض صدرية وجهاز تنفسي فوراً لتلقي العلاج المناسب والمتابعة.'
                    : 'الرئة تبدو سليمة وخالية من الالتهاب الرئوي. يرجى الراحة واستشارة الطبيب إذا استمرت الأعراض.',
                BoneNameAr: repAr.disease_name || repAr.bone_name || '',
                SeverityAr: repAr.severity || '',
                MedicalReportAr: repAr.report || '',
                TreatmentPlanAr: repAr.treatment_plan || '',

                // English fields
                DiagnosisEn: predTextEn,
                RecommendationsEn: isAbnormalEn
                    ? 'Please consult a pulmonologist / chest specialist immediately for treatment and follow-up.'
                    : 'Lungs appear clear and healthy. Rest and consult a doctor if symptoms persist.',
                BoneNameEn: repEn.disease_name || repEn.bone_name || '',
                SeverityEn: repEn.severity || '',
                MedicalReportEn: repEn.report || '',
                TreatmentPlanEn: repEn.treatment_plan || '',

                // Standard fallback fields (based on active lang at scan time)
                Diagnosis: lang === 'ar' ? predTextAr : predTextEn,
                Recommendations: lang === 'ar'
                    ? (isAbnormalAr ? 'يرجى مراجعة طبيب أمراض صدرية وجهاز تنفسي فوراً.' : 'الرئة تبدو سليمة وخالية من الالتهاب. يرجى الراحة واستشارة الطبيب عند الحاجة.')
                    : (isAbnormalEn ? 'Please consult a pulmonologist immediately.' : 'Lungs appear clear and healthy. Rest and consult a doctor if needed.'),
                BoneName: lang === 'ar' ? (repAr.disease_name || '') : (repEn.disease_name || ''),
                Severity: lang === 'ar' ? (repAr.severity || '') : (repEn.severity || ''),
                MedicalReport: lang === 'ar' ? (repAr.report || '') : (repEn.report || ''),
                TreatmentPlan: lang === 'ar' ? (repAr.treatment_plan || '') : (repEn.treatment_plan || ''),
                Heatmap: hfDataEn.heatmap || hfDataAr.heatmap || '',
                _lang: lang
            };

            result = {
                scanType: scanType,
                fileName: selectedFile.name,
                filePath: '',
                aiResult: JSON.stringify(aiResultObj),
                createdAt: new Date().toISOString()
            };

            // Also save to backend database (fire-and-forget, don't block the UI)
            try {
                const saveFormData = new FormData();
                saveFormData.append('file', selectedFile);
                saveFormData.append('scanType', scanType);
                saveFormData.append('Lang', lang);
                Api.diagnosis.analyze(saveFormData).catch(e => console.warn('[AI] Backend save warning:', e.message));
            } catch(saveErr) {
                console.warn('[AI] Backend save skipped:', saveErr.message);
            }

        } else if (scanType === 'brain_neurology') {
            // === DIRECT call to Hugging Face Space for Brain Tumor MRI ===
            const hfFormData = new FormData();
            hfFormData.append('file', selectedFile);
            hfFormData.append('model_type', 'ensemble');

            console.log('[AI] Sending to Brain Tumor HF Space directly...');
            const hfResponse = await fetch('https://khaledai123-brain-tumor-mri-model.hf.space/predict', {
                method: 'POST',
                body: hfFormData
            });

            if (!hfResponse.ok) {
                throw new Error(lang === 'ar'
                    ? `فشل الاتصال بخدمة الذكاء الاصطناعي (HTTP ${hfResponse.status})`
                    : `AI service connection failed (HTTP ${hfResponse.status})`);
            }

            const hfData = await hfResponse.json();
            console.log('[AI] Brain Tumor HF Space response received:', hfData);

            // Check if image is a valid brain MRI
            if (hfData.is_valid_mri === false) {
                throw new Error(lang === 'ar'
                    ? (hfData.warning_ar || 'الصورة المرفوعة ليست أشعة رنين مغناطيسي للدماغ. يرجى رفع صورة صحيحة.')
                    : (hfData.warning_en || 'The uploaded image is not a Brain MRI scan. Please upload a valid scan.'));
            }

            let confidencePercent = hfData.confidence;
            if (typeof confidencePercent === 'number') {
                if (confidencePercent <= 1.0) confidencePercent = Math.round(confidencePercent * 100);
                else confidencePercent = Math.round(confidencePercent);
            } else {
                confidencePercent = 90;
            }

            const tumorFound = hfData.tumor_present;
            const medReport = hfData.medical_report || {};

            // Build bilingual aiResult for language-aware rendering
            const aiResultObj = {
                _isBilingual: true,
                Confidence: confidencePercent + '%',

                // Arabic diagnosis fields
                DiagnosisAr: hfData.arabic_label || (tumorFound ? 'تم اكتشاف ورم في المخ' : 'لا يوجد ورم - المخ سليم'),
                RecommendationsAr: tumorFound
                    ? 'يرجى مراجعة طبيب المخ والأعصاب فوراً لعمل الفحوصات اللازمة ومناقشة الخطة العلاجية.'
                    : 'نتائج الأشعة سليمة. يرجى المتابعة الدورية مع طبيب المخ والأعصاب.',
                BoneNameAr: medReport.tumor_type_ar || hfData.arabic_label || (tumorFound ? 'ورم دماغي' : 'مخ سليم'),
                SeverityAr: medReport.severity_level_ar || (tumorFound ? 'حرج' : 'طبيعي'),
                MedicalReportAr: medReport.medical_description_ar || (tumorFound ? 'كشف تحليل الذكاء الاصطناعي عن وجود منطقة غير طبيعية تشير إلى ورم دماغي.' : 'التحليل أظهر أنسجة دماغية طبيعية وخالية من الأورام.'),
                TreatmentPlanAr: medReport.treatment_plan_ar || (tumorFound ? '1. استشارة عاجلة مع جراح مخ وأعصاب.\n2. إجراء رنين مغناطيسي بالصبغة لتحديد الحجم بدقة.' : '1. لا توجد حاجة لتدخل علاجي فوري.\n2. المتابعة الدورية عند الحاجة.'),

                // English diagnosis fields
                DiagnosisEn: hfData.label || hfData.classification || (tumorFound ? 'Brain Tumor Detected' : 'No Tumor - Healthy Brain'),
                RecommendationsEn: tumorFound
                    ? 'Please consult a neurosurgeon immediately for further tests and treatment plan.'
                    : 'MRI results appear normal. Continue regular check-ups with your neurologist.',
                BoneNameEn: medReport.tumor_type_en || hfData.label || hfData.classification || (tumorFound ? 'Brain Tumor' : 'Healthy Brain'),
                SeverityEn: medReport.severity_level_en || (tumorFound ? 'Critical' : 'Normal'),
                MedicalReportEn: medReport.medical_description_en || (tumorFound ? 'AI analysis indicates a suspicious region consistent with a brain tumor.' : 'MRI scan indicates normal brain tissue architecture with no signs of pathological masses.'),
                TreatmentPlanEn: medReport.treatment_plan_en || (tumorFound ? '1. Immediate consultation with a neurosurgeon.\n2. Contrast-enhanced MRI scan for size definition.' : '1. No immediate clinical intervention required.\n2. Regular check-ups as needed.'),

                // Standard fallback fields (based on active lang at scan time)
                Diagnosis: lang === 'ar'
                    ? (hfData.arabic_label || (tumorFound ? 'تم اكتشاف ورم في المخ' : 'لا يوجد ورم - المخ سليم'))
                    : (hfData.label || hfData.classification || (tumorFound ? 'Brain Tumor Detected' : 'No Tumor - Healthy Brain')),
                Recommendations: lang === 'ar'
                    ? (tumorFound ? 'يرجى مراجعة طبيب المخ والأعصاب فوراً.' : 'نتائج الأشعة سليمة. يرجى المتابعة الدورية.')
                    : (tumorFound ? 'Please consult a neurosurgeon immediately.' : 'MRI results appear normal.'),
                BoneName: lang === 'ar'
                    ? (medReport.tumor_type_ar || hfData.arabic_label || (tumorFound ? 'ورم دماغي' : 'مخ سليم'))
                    : (medReport.tumor_type_en || hfData.label || (tumorFound ? 'Brain Tumor' : 'Healthy Brain')),
                Severity: lang === 'ar'
                    ? (medReport.severity_level_ar || (tumorFound ? 'حرج' : 'طبيعي'))
                    : (medReport.severity_level_en || (tumorFound ? 'Critical' : 'Normal')),
                MedicalReport: lang === 'ar'
                    ? (medReport.medical_description_ar || (tumorFound ? 'كشف تحليل الذكاء الاصطناعي عن وجود منطقة غير طبيعية.' : 'التحليل أظهر أنسجة دماغية طبيعية.'))
                    : (medReport.medical_description_en || (tumorFound ? 'AI analysis indicates a suspicious brain region.' : 'Normal brain tissue with no signs of masses.')),
                TreatmentPlan: lang === 'ar'
                    ? (medReport.treatment_plan_ar || (tumorFound ? '1. استشارة عاجلة مع جراح مخ وأعصاب.' : '1. لا توجد حاجة لتدخل فوري.'))
                    : (medReport.treatment_plan_en || (tumorFound ? '1. Immediate neurosurgeon consultation.' : '1. No immediate intervention required.')),
                Heatmap: hfData.gradcam_image || '',
                _lang: lang
            };

            result = {
                scanType: scanType,
                fileName: selectedFile.name,
                filePath: '',
                aiResult: JSON.stringify(aiResultObj),
                createdAt: new Date().toISOString()
            };

            // Fire-and-forget: save to backend database without blocking the UI
            try {
                const saveFormData = new FormData();
                saveFormData.append('file', selectedFile);
                saveFormData.append('scanType', scanType);
                saveFormData.append('Lang', lang);
                Api.diagnosis.analyze(saveFormData).catch(e => console.warn('[AI] Backend save warning:', e.message));
            } catch(saveErr) {
                console.warn('[AI] Backend save skipped:', saveErr.message);
            }

        } else {
            // === Go through C# Backend for AI analysis and storage ===
            const formData = new FormData();
            formData.append('file', selectedFile);
            formData.append('scanType', scanType);
            formData.append('Lang', lang);
            result = await Api.diagnosis.analyze(formData);
        }

        // Parse and check for validation warnings (e.g. invalid MRI scan)
        const parsedReport = parseAIResult(result.aiResult, lang);
        if (parsedReport._error_message) {
            throw new Error(parsedReport._error_message);
        }

        // Display results
        renderScanResult(result);

        // Switch UI to result area
        analysisLoader.classList.add('d-none');
        analyzeBtn.classList.remove('d-none');
        resultArea.classList.remove('d-none');
        
        resultArea.scrollIntoView({ behavior: 'smooth' });

    } catch (error) {
        console.error('Analysis error:', error);
        analysisLoader.classList.add('d-none');
        analyzeBtn.classList.remove('d-none');
        showAlert(error.message || (lang === 'ar' ? 'حدث خطأ أثناء التحليل.' : 'Analysis error occurred. Please try again.'), 'error');
    } finally {
        progress.style.width = '0%';
    }
});

async function loadExistingReport(id) {
    const lang = localStorage.getItem('mediai_lang') || 'en';
    const analysisLoader = document.getElementById('analysisLoader');
    const resultArea = document.getElementById('resultArea');
    const stepSelection = document.getElementById('stepSelection');

    stepSelection.classList.add('d-none');
    analysisLoader.classList.remove('d-none');

    // Check if we should auto-print after loading
    const urlParams = new URLSearchParams(window.location.search);
    const autoPrint = urlParams.get('print') === '1';

    try {
        const result = await Api.diagnosis.getById(id);
        renderScanResult(result);

        // Auto-generate PDF if print=1 was in the URL
        if (autoPrint) {
            // Small delay to let the DOM fully render before printing
            setTimeout(() => {
                window.generateMedicalReport && window.generateMedicalReport();
            }, 600);
        }
    } catch (e) {
        console.error('Fetch error:', e);
        showAlert(lang === 'ar' ? 'تعذر تحميل التقرير.' : 'Could not load report.', 'error');
        stepSelection.classList.remove('d-none');
    } finally {
        analysisLoader.classList.add('d-none');
    }
}


function renderScanResult(result) {
    const resultArea = document.getElementById('resultArea');
    const lang = localStorage.getItem('mediai_lang') || 'en';
    
    // Set scanType value globally so report printing can access it
    if (result.scanType) {
        document.getElementById('scanType').value = result.scanType;
        const examTitleEl = document.getElementById('selectedExamTitle');
        if (examTitleEl) {
            let title = '...';
            if (result.scanType === 'xray_bone') title = lang === 'ar' ? 'أشعة سينية (كسور العظام)' : 'X-Ray (Bone Fracture)';
            else if (result.scanType === 'ecg_heart') title = lang === 'ar' ? 'أشعة الصدر (الالتهاب الرئوي)' : 'X-Ray (Pneumonia)';
            else if (result.scanType === 'brain_neurology') title = lang === 'ar' ? 'أورام المخ (الرنين المغناطيسي)' : 'Brain Tumors (MRI)';
            examTitleEl.textContent = title;
        }
    }
    
    // Parse the complex AI result string if it's JSON
    const report = parseAIResult(result.aiResult);
    window.lastScanReport = report;
    
    // Comprehensive content translation layer
    const severityMap = {
        "Normal": { ar: "طبيعي", en: "Normal" },
        "Warning": { ar: "تحذير", en: "Warning" },
        "Critical": { ar: "حرج", en: "Critical" }
    };
    const detailMap = {
        "No Fractures Detected": { ar: "لم يتم اكتشاف كسور", en: "No Fractures Detected" },
        "Hairline Fracture Detected": { ar: "تم اكتشاف كسر شعري", en: "Hairline Fracture Detected" },
        "Healthy Bone Structure": { ar: "هيكل عظمي سليم", en: "Healthy Bone Structure" },
        "Comminuted Fracture Detected": { ar: "تم اكتشاف كسر مفتت", en: "Comminuted Fracture Detected" },
        "Osteoporosis Signs Detected": { ar: "تم اكتشاف علامات هشاشة عظام", en: "Osteoporosis Signs Detected" },
        "Bone Spur Detected": { ar: "تم اكتشاف نتوء عظمي", en: "Bone Spur Detected" },
        "Sinus Rhythm": { ar: "نظم الجيب السليم", en: "Sinus Rhythm" },
        "Arrhythmia Detected": { ar: "تم اكتشاف عدم انتظام ضربات القلب", en: "Arrhythmia Detected" },
        "ST Elevation Detected": { ar: "تم اكتشاف ارتفاع في مقطع ST", en: "ST Elevation Detected" },
        "T-Wave Inversion Detected": { ar: "تم اكتشاف انقلاب الموجة T", en: "T-Wave Inversion Detected" },
        "Left Ventricular Hypertrophy": { ar: "تضخم البطين الأيسر", en: "Left Ventricular Hypertrophy" },
        "Normal Heart Activity": { ar: "نشاط قلبي طبيعي", en: "Normal Heart Activity" },
        "No Abnormalities": { ar: "لا توجد تشوهات", en: "No Abnormalities" },
        "Suspicious Mass Detected": { ar: "تم اكتشاف كتلة مشبوهة", en: "Suspicious Mass Detected" },
        "Malignant Tumor Detected": { ar: "تم اكتشاف ورم خبيث", en: "Malignant Tumor Detected" },
        "Metabolic Activity Normal": { ar: "النشاط الأيضي طبيعي", en: "Metabolic Activity Normal" },
        "Cerebral Atrophy Signs": { ar: "علامات ضمور دماغي", en: "Cerebral Atrophy Signs" },
        "White Matter Lesions Detected": { ar: "تم اكتشاف آفات في المادة البيضاء", en: "White Matter Lesions Detected" },
        "Non-fractured": { ar: "غير مكسور", en: "Non-fractured" },
        "Fracture Detected": { ar: "تم اكتشاف كسر", en: "Fracture Detected" },
        "No Fracture": { ar: "لا يوجد كسر", en: "No Fracture" },
        "Healthy": { ar: "سليم", en: "Healthy" },
        "Fractured": { ar: "مكسورة", en: "Fractured" },
        "Displaced": { ar: "مع إزاحة", en: "Displaced" },
        "Severe": { ar: "شديدة", en: "Severe" },
        "Comminuted": { ar: "مفتت", en: "Comminuted" }
    };
    // Extra Arabic→English mappings for common HF response terms
    const arToEnMap = {
        "مكسورة": "Fractured",
        "مكسور": "Fractured",
        "كسر": "Fracture",
        "سليمة": "Healthy",
        "سليم": "Healthy",
        "شديدة": "Severe",
        "شديد": "Severe",
        "مفتت": "Comminuted",
        "إزاحة": "Displacement",
        "متزاحة": "Displaced",
        "عظم": "Bone",
        "الزند": "Ulna",
        "الكعبرة": "Radius",
        "الساعد": "Forearm",
        "كسر مضاعف": "Comminuted Fracture",
        "جراحي": "Surgical",
        "علاجي": "Therapeutic",
        "توصيات": "Recommendations",
        "تشخيص": "Diagnosis",
        "طبيعي": "Normal",
        "تحذير": "Warning",
        "حرج": "Critical",
        "ورم": "Tumor",
        "القلب": "Heart",
        "قلبي": "Cardiac"
    };
    const phraseMap = {
        "Preliminary analysis indicates normal findings.": { ar: "يشير التحليل الأولي إلى نتائج طبيعية وسليمة تماماً.", en: "Preliminary analysis indicates normal findings." },
        "Consult a specialist for a detailed review.": { ar: "يرجى استشارة طبيب مختص للمراجعة الدقيقة وتأكيد النتائج.", en: "Consult a specialist for a detailed review." },
        "Normal Findings": { ar: "نتائج طبيعية", en: "Normal Findings" }
    };

    function translateContent(text, targetLang) {
        if (!text) return text;
        // If target is Arabic, try to translate English → Arabic
        if (targetLang === 'ar') {
            // Check if already mostly Arabic (contains Arabic Unicode chars)
            let arabicCount = (text.match(/[\u0600-\u06FF]/g) || []).length;
            if (arabicCount > text.length * 0.3) return text;
            // Try full phrase match
            for (const [phrase, langs] of Object.entries(phraseMap)) {
                if (text === phrase || text.trim() === phrase) return langs.ar;
            }
            // Try detail match
            for (const [detail, langs] of Object.entries(detailMap)) {
                if (text.includes(detail)) return text.replace(detail, langs.ar);
            }
            // Try severity match
            let translated = text;
            for (const [sev, langs] of Object.entries(severityMap)) {
                if (translated.includes(sev)) { translated = translated.replace(sev, langs.ar); break; }
            }
            return translated;
        }
        // If target is English, try to translate Arabic → English
        if (targetLang === 'en') {
            if (!(/[\u0600-\u06FF]/).test(text)) return text;
            // Strategy: extract English text from parentheses (HF Space returns Arabic(English) format)
            const parenTexts = [];
            const parenRegex = /\(([^)]*)\)/g;
            let m;
            while ((m = parenRegex.exec(text)) !== null) {
                const content = m[1].trim();
                if (content && !(/[\u0600-\u06FF]/).test(content)) {
                    parenTexts.push(content);
                }
            }
            if (parenTexts.length > 0) return parenTexts.join(', ');
            // Try word-level replacement
            const origArabicCount = (text.match(/[\u0600-\u06FF]/g) || []).length;
            const reverseMap = { ...arToEnMap };
            for (const [, langs] of Object.entries(detailMap)) {
                reverseMap[langs.ar] = langs.en;
            }
            for (const [, langs] of Object.entries(severityMap)) {
                reverseMap[langs.ar] = langs.en;
            }
            const sortedKeys = Object.keys(reverseMap).sort((a, b) => b.length - a.length);
            for (const arKey of sortedKeys) {
                if (text.includes(arKey)) text = text.replace(arKey, reverseMap[arKey]);
            }
            text = text.replace(/\s{2,}/g, ' ').trim();
            const newArabicCount = (text.match(/[\u0600-\u06FF]/g) || []).length;
            if (newArabicCount <= origArabicCount * 0.5) return text;
            return text;
        }
        return text;
    }

    let diagnosis = report.diagnosis || 'Unknown';
    let recommendations = report.recommendations || '';
    
    // Check if stored language differs from display language
    const storedLang = report._lang || 'en';
    const needsFullTranslation = storedLang !== lang;
    
    if (needsFullTranslation) {
        // Translate short fields using word maps
        diagnosis = translateContent(diagnosis, lang);
        recommendations = translateContent(recommendations, lang);
        report.severity = translateContent(report.severity || '', lang);
        report.boneName = translateContent(report.boneName || '', lang);
        report.fractureType = translateContent(report.fractureType || '', lang);
        // For long paragraphs: only translate if the target is Arabic
        if (lang === 'ar') {
            report.medicalReport = translateContent(report.medicalReport || '', lang);
            report.treatmentPlan = translateContent(report.treatmentPlan || '', lang);
        }
    } else {
        // Same language — apply translateContent anyway for seed data coverage
        diagnosis = translateContent(diagnosis, lang);
        recommendations = translateContent(recommendations, lang);
        report.severity = translateContent(report.severity || '', lang);
        report.boneName = translateContent(report.boneName || '', lang);
        report.fractureType = translateContent(report.fractureType || '', lang);
    }

    const confidence = parseInt(report.confidence) || 95; 

    // Update UI elements
    document.getElementById('detectedCondition').innerHTML = diagnosis;
    
    // Map Scan Types to Specialties for Booking
    const scanType = document.getElementById('scanType').value;
    const specMap = {
        'ecg_heart': 'Pneumonia',
        'xray_bone': 'Orthopedics',
        'brain_neurology': 'Neurology'
    };
    const targetSpec = specMap[scanType] || '';

    // Premium Medical Explanation / Findings
    const explanationBox = document.getElementById('medicalExplanation');
    
    let explanationHTML = `
        <div class="premium-findings-box p-4 rounded-4 shadow-sm border-start border-4 border-primary bg-white mb-3">
            <h6 class="fw-bold text-primary mb-3 d-flex align-items-center gap-2">
                <i class="bi bi-clipboard2-pulse"></i>
                ${translations[lang].findings_label}
            </h6>
            <p class="mb-0 text-dark lh-base" style="font-size: 1.1rem; text-align: justify;">${diagnosis}</p>
        </div>
    `;

    // Render detailed report card if any details are returned from HF Space
    if (report.boneName || report.fractureType || report.severity || report.medicalReport || report.treatmentPlan || report.heatmap) {
        let sevClass = "bg-warning-subtle text-warning border border-warning-subtle";
        if (report.severity && (report.severity.includes("شديد") || report.severity.toLowerCase().includes("high") || report.severity.toLowerCase().includes("severe"))) {
            sevClass = "bg-danger-subtle text-danger border border-danger-subtle";
        } else if (report.severity && (report.severity.includes("بسيط") || report.severity.toLowerCase().includes("low") || report.severity.toLowerCase().includes("mild"))) {
            sevClass = "bg-success-subtle text-success border border-success-subtle";
        }

        explanationHTML += `
            <div class="detailed-report-card p-4 rounded-4 shadow-sm border border-light bg-white mt-4 reveal-up visible">
                <h5 class="fw-bold text-dark mb-4 pb-2 border-bottom d-flex align-items-center gap-2">
                    <i class="bi bi-file-earmark-medical text-primary fs-4"></i>
                    ${lang === 'ar' ? '🩺 التقرير الطبي المفصل' : '🩺 Detailed Medical Report'}
                </h5>
                <div class="row g-3 mb-4">
                    ${report.boneName ? `
                        <div class="col-md-6">
                            <span class="text-muted small d-block mb-1">
                                ${scanType === 'brain_neurology' 
                                    ? (lang === 'ar' ? '🧠 البنية التشريحية المتأثرة' : '🧠 Affected Anatomy')
                                    : (scanType === 'ecg_heart'
                                        ? (lang === 'ar' ? '🫁 البنية التشريحية' : '🫁 Anatomy / Condition')
                                        : (lang === 'ar' ? '🦴 العظمة المتأثرة' : '🦴 Affected Bone'))
                                }
                            </span>
                            <span class="fw-bold text-dark fs-6 bg-light px-3 py-2 rounded-3 d-inline-block border">
                                <i class="${scanType === 'brain_neurology' ? 'fa-solid fa-brain' : (scanType === 'ecg_heart' ? 'fa-solid fa-lungs' : 'fa-solid fa-bone')} text-primary me-2"></i>
                                ${report.boneName}
                            </span>
                        </div>
                    ` : ''}
                    ${report.fractureType ? `
                        <div class="col-md-6">
                            <span class="text-muted small d-block mb-1">
                                ${scanType === 'ecg_heart'
                                    ? (lang === 'ar' ? '⚡ نوع الإصابة' : '⚡ Condition / Disease')
                                    : (lang === 'ar' ? '⚡ نوع الكسر' : '⚡ Fracture Type')
                                }
                            </span>
                            <span class="fw-bold text-dark fs-6 bg-light px-3 py-2 rounded-3 d-inline-block border"><i class="fa-solid fa-bolt text-warning me-2"></i>${report.fractureType}</span>
                        </div>
                    ` : ''}
                    ${report.severity ? `
                        <div class="col-md-6">
                            <span class="text-muted small d-block mb-1">${lang === 'ar' ? '⚠️ درجة الخطورة' : '⚠️ Severity'}</span>
                            <span class="badge ${sevClass} px-3 py-2 fs-6 rounded-pill d-inline-flex align-items-center gap-2 mt-1">
                                <span class="spinner-grow spinner-grow-sm" style="animation-duration: 1.5s;" role="status"></span>
                                ${report.severity}
                            </span>
                        </div>
                    ` : ''}
                </div>
                
                ${report.medicalReport ? `
                    <div class="mt-4 p-3 bg-light rounded-4 border">
                        <span class="text-muted small fw-bold d-block mb-2 text-uppercase tracking-wider" style="font-size: 0.75rem;">${lang === 'ar' ? '📝 الوصف الطبي الفني' : '📝 Technical Medical Description'}</span>
                        <p class="mb-0 text-dark lh-base" style="font-size: 1rem; text-align: justify;">${report.medicalReport}</p>
                    </div>
                ` : ''}
                
                ${report.treatmentPlan ? `
                    <div class="mt-3 p-3 rounded-4 border border-success-subtle bg-light">
                        <span class="text-success small fw-bold d-block mb-2 text-uppercase tracking-wider" style="font-size: 0.75rem;">
                            <i class="bi bi-capsule-capsule me-1"></i>
                            ${lang === 'ar' ? '💊 الخطة العلاجية والتوصيات المقترحة' : '💊 Suggested Treatment Plan & Recommendations'}
                        </span>
                        <p class="mb-0 text-dark lh-base" style="font-size: 1rem; text-align: justify;">${report.treatmentPlan}</p>
                    </div>
                ` : ''}

                ${report.heatmap ? `
                    <div class="mt-4 pt-3 border-top text-center">
                        <span class="text-muted small fw-bold d-block mb-3 text-uppercase tracking-wider" style="font-size: 0.75rem;">
                            <i class="bi bi-search me-1"></i>
                            ${lang === 'ar' ? '🔍 خريطة كشف موقع الإصابة والتظليل الحراري (Grad-CAM)' : '🔍 Location of Injury Heatmap Visualization (Grad-CAM)'}
                        </span>
                        <div class="heatmap-img-wrapper p-2 bg-light border rounded-4 d-inline-block shadow-sm">
                            <img src="data:image/jpeg;base64,${report.heatmap}" class="img-fluid rounded-3" style="max-height: 380px; object-fit: contain; display: block;" alt="Grad-CAM Heatmap" />
                        </div>
                    </div>
                ` : ''}
            </div>
        `;
    }

    explanationBox.innerHTML = explanationHTML;

    // Recommended Actions Specialist
    const recBox = document.getElementById('recommendedSpecialist');
    const displaySpec = translateSpecialty(targetSpec);
    recBox.innerHTML = `
        <div class="d-flex align-items-center gap-2">
            <i class="bi bi-person-check fs-4"></i>
            <span>${displaySpec || (lang === 'ar' ? 'لا توجد توصيات محددة' : 'No specific recommendations')}</span>
        </div>
    `;

    // Update Book Consultation Link
    const bookBtn = document.querySelector('[data-lang="btn_book_specialist"]');
    if (bookBtn) {
        bookBtn.href = `../doctors/doctors.html?specialty=${targetSpec}`;
    }

    // NEW: Load Suggested Doctors
    loadSuggestedDoctors(targetSpec);
    
    // Confidence Ring Micro-Animation
    const levelText = document.getElementById('confidenceLevel');
    const stroke = document.getElementById('confidenceStroke');
    
    let counter = 0;
    levelText.textContent = '0%';
    stroke.setAttribute('stroke-dasharray', '0, 100');
    
    const ringTimer = setInterval(() => {
        if (counter >= confidence) {
            clearInterval(ringTimer);
        } else {
            counter++;
            levelText.textContent = counter + '%';
            stroke.setAttribute('stroke-dasharray', `${counter}, 100`);
        }
    }, 15);

    // Show result with animation
    resultArea.classList.remove('d-none');
    resultArea.classList.add('reveal-up', 'visible');
    resultArea.scrollIntoView({ behavior: 'smooth' });
}

async function loadSuggestedDoctors(specialty) {
    const section = document.getElementById('suggestedDoctorsSection');
    const row = document.getElementById('suggestedDoctorsRow');
    if (!section || !row) return;

    row.innerHTML = '<div class="col-12 text-center py-3"><div class="spinner-border spinner-border-sm text-primary"></div></div>';
    section.classList.remove('d-none');

    try {
        const data = await Api.doctors.getAll(`specialty=${specialty}`);
        let doctors = Array.isArray(data) ? data : (data.doctors || []);
        
        // Translate doctor names
        const diagLang = localStorage.getItem('mediai_lang') || 'en';
        doctors = doctors.map(d => ({
            ...d,
            fullName: translateDoctorName(d.fullName || d.name, diagLang),
            name: translateDoctorName(d.fullName || d.name, diagLang)
        }));

        row.innerHTML = '';
        
        if (doctors.length === 0) {
            section.classList.add('d-none');
            return;
        }

        // Show top 3
        const lang = localStorage.getItem('mediai_lang') || 'en';
        doctors.slice(0, 3).forEach(doc => {
            const col = document.createElement('div');
            col.className = 'col-md-4';
            col.innerHTML = `
                <div class="card h-100 border-0 shadow-sm rounded-4 overflow-hidden suggest-doc-card bg-light">
                    <div class="card-body p-3">
                        <div class="d-flex align-items-center gap-3 mb-3">
                            <div class="doc-mini-avatar bg-primary text-white rounded-circle d-flex align-items-center justify-content-center fw-bold shadow-sm" style="width: 45px; height: 45px; font-size: 0.9rem;">
                                ${doc.fullName.split(' ').map(n=>n[0]).join('').slice(0,2).toUpperCase()}
                            </div>
                            <div class="overflow-hidden">
                                <h6 class="fw-bold mb-0 text-truncate">${doc.fullName}</h6>
                                <p class="text-muted small mb-0">${doc.experienceYears}+ ${lang === 'ar' ? 'سنة خبرة' : 'years exp'}</p>
                            </div>
                        </div>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="text-warning small fw-bold">
                                <i class="bi bi-star-fill"></i> ${doc.rating || 5.0}
                            </div>
                            <a href="../booking/booking.html?doc=${doc.id}" class="btn btn-primary btn-sm rounded-pill px-3 fw-bold" style="font-size: 0.75rem;">
                                ${translations[lang].doc_btn_book}
                            </a>
                        </div>
                    </div>
                </div>
            `;
            row.appendChild(col);
        });

    } catch (err) {
        console.error('Failed to load suggested doctors:', err);
        section.classList.add('d-none');
    }
}

function parseAIResult(raw, activeLang) {
    const lang = activeLang || localStorage.getItem('mediai_lang') || 'en';
    if (!raw) return { diagnosis: 'Unknown', confidence: '0%', recommendations: 'None', boneName: '', fractureType: '', severity: '', medicalReport: '', treatmentPlan: '', heatmap: '', _lang: lang };
    
    try {
        const parsed = JSON.parse(raw);
        
        // Handle bilingual format returned by updated models
        if (parsed._isBilingual) {
            return {
                diagnosis: lang === 'ar' ? (parsed.DiagnosisAr || parsed.Diagnosis) : (parsed.DiagnosisEn || parsed.Diagnosis),
                confidence: parsed.Confidence || '90%',
                recommendations: lang === 'ar' ? (parsed.RecommendationsAr || parsed.Recommendations) : (parsed.RecommendationsEn || parsed.Recommendations),
                boneName: lang === 'ar' ? (parsed.BoneNameAr || parsed.BoneName || '') : (parsed.BoneNameEn || parsed.BoneName || ''),
                fractureType: parsed.FractureType || parsed.fracture_type || '',
                severity: lang === 'ar' ? (parsed.SeverityAr || parsed.Severity) : (parsed.SeverityEn || parsed.Severity),
                medicalReport: lang === 'ar' ? (parsed.MedicalReportAr || parsed.MedicalReport) : (parsed.MedicalReportEn || parsed.MedicalReport),
                treatmentPlan: lang === 'ar' ? (parsed.TreatmentPlanAr || parsed.TreatmentPlan) : (parsed.TreatmentPlanEn || parsed.TreatmentPlan),
                heatmap: parsed.Heatmap || parsed.heatmap || '',
                _error_message: parsed._error_message || '',
                _lang: lang
            };
        }

        // Standard parsing fallback
        let storedLang = parsed._lang || parsed._Language || '';
        if (!storedLang) {
            // Auto-detect from content
            const allText = (parsed.Diagnosis || parsed.diagnosis || '') +
                            (parsed.MedicalReport || parsed.medicalReport || '') +
                            (parsed.Recommendations || parsed.recommendations || '');
            storedLang = (/[\u0600-\u06FF]/).test(allText) ? 'ar' : 'en';
        }
        return {
            diagnosis: parsed.Diagnosis || parsed.diagnosis || 'Unknown',
            confidence: parsed.Confidence || parsed.confidence || '90%',
            recommendations: parsed.Recommendations || parsed.recommendations || '',
            boneName: parsed.BoneName || parsed.bone_name || '',
            fractureType: parsed.FractureType || parsed.fracture_type || '',
            severity: parsed.Severity || parsed.severity || '',
            medicalReport: parsed.MedicalReport || parsed.report || parsed.medicalReport || '',
            treatmentPlan: parsed.TreatmentPlan || parsed.treatment_plan || parsed.treatmentPlan || '',
            heatmap: parsed.Heatmap || parsed.heatmap || '',
            _error_message: parsed._error_message || '',
            _lang: storedLang
        };
    } catch (e) {
        const hasArabic = (/[\u0600-\u06FF]/).test(raw);
        return {
            diagnosis: raw,
            confidence: '90%',
            recommendations: '',
            boneName: '',
            fractureType: '',
            severity: '',
            medicalReport: '',
            treatmentPlan: '',
            heatmap: '',
            _lang: hasArabic ? 'ar' : 'en'
        };
    }
}

// Auth Guard Check & Deep Link Parsing
document.addEventListener('DOMContentLoaded', () => {
    const role = localStorage.getItem('mediai_auth_role');
    if (!role) {
        window.location.href = '../login/login.html?redirect=../diagnosis/diagnosis.html';
        return;
    }

    initReveals();
    
    // Check URL for id parameter (View existing report)
    const urlParams = new URLSearchParams(window.location.search);
    const idParam = urlParams.get('id');
    const typeParam = urlParams.get('type');
    
    if (idParam) {
        loadExistingReport(idParam);
        return; // Don't process other params if loading an ID
    }
    
    if (typeParam) {
        // Find the card element that corresponds to this type
        const card = document.querySelector(`[onclick*="'${typeParam}'"]`);
        if (card) {
            let iconClass = '';
            if (typeParam === 'xray_bone') iconClass = 'bi-person-bounding-box';
            else if (typeParam === 'skin_lesion') iconClass = 'bi-fingerprint';
            else if (typeParam === 'ecg_heart') iconClass = 'fa-solid fa-lungs';
            else if (typeParam === 'brain_neurology') iconClass = 'bi-brain';
            else if (typeParam === 'pdf_report') iconClass = 'bi-file-medical';
            
            setTimeout(() => {
                selectScanType(typeParam, card, iconClass);
                // Clean up URL so it doesn't linger on refresh
                window.history.replaceState({}, document.title, window.location.pathname);
            }, 100);
        }
    }
});

// Re-render scan result when language changes dynamically
document.addEventListener('languageChanged', () => {
    const resultArea = document.getElementById('resultArea');
    if (resultArea && !resultArea.classList.contains('d-none')) {
        const conditionEl = document.getElementById('detectedCondition');
        if (conditionEl && conditionEl.textContent !== '...') {
            const idParam = new URLSearchParams(window.location.search).get('id');
            if (idParam) loadExistingReport(idParam);
        }
    }
});

// Card Selection & Wizard Logic
window.selectScanType = function(type, element, iconClass) {
    document.getElementById('scanType').value = type;
    
    // Get title from card
    const title = element.querySelector('h6').textContent;
    
    // Update Step 2 UI
    document.getElementById('selectedExamTitle').textContent = title;
    
    const iconEl = document.getElementById('selectedExamIcon');
    iconEl.className = 'fs-4 ' + iconClass;
    
    // Map colors to the icon container based on type
    const container = document.getElementById('selectedExamIconContainer');
    container.className = 'bg-white p-3 rounded-circle shadow-sm border ';
    if (type === 'xray_bone') container.classList.add('text-primary');
    else if (type === 'skin_lesion') container.classList.add('text-success');
    else if (type === 'ecg_heart') container.classList.add('text-danger');
    else if (type === 'brain_neurology') container.classList.add('text-purple');
    else if (type === 'pdf_report') container.classList.add('text-secondary');
    
    // Proceed to Step 2
    document.getElementById('stepSelection').classList.add('d-none');
    document.getElementById('stepUpload').classList.remove('d-none');
    
    // Clear previous results/previews if any
    document.getElementById('resultArea').classList.add('d-none');
    
    // Scroll to top of upload zone softly
    document.getElementById('stepUpload').scrollIntoView({ behavior: 'smooth', block: 'start' });
    
    // Check if file is already uploaded, auto-analyze
    if (selectedFile) {
        setTimeout(() => document.getElementById('analyzeBtn').click(), 300);
    }
};

window.reselectScanType = function() {
    document.getElementById('stepUpload').classList.add('d-none');
    document.getElementById('stepSelection').classList.remove('d-none');
    document.getElementById('resultArea').classList.add('d-none');
    document.getElementById('scanType').value = '';
    
    document.getElementById('stepSelection').scrollIntoView({ behavior: 'smooth', block: 'start' });
};

window.resetFullScan = function() {
    // Clear URL parameters if any so we don't auto-trigger a shortcut again
    window.history.replaceState({}, document.title, window.location.pathname);
    
    // Clear preview and file selection entirely
    clearPreview();
    
    // Return to the first screen
    reselectScanType();
};

window.generateMedicalReport = async function() {
    const refNo = Math.floor(Math.random() * 900000) + 100000;
    const report = window.lastScanReport || {};
    const lang = localStorage.getItem('mediai_lang') || 'en';

    // Retrieve initial cached data
    let name = localStorage.getItem('mediai_user_name') || 'Patient Name';
    let email = localStorage.getItem('mediai_user_email') || 'N/A';
    let phone = localStorage.getItem('mediai_user_phone') || '—';
    let age = localStorage.getItem('mediai_user_age') || '—';
    let gender = localStorage.getItem('mediai_user_gender') || '—';

    // Fetch updated complete profile dynamically from backend auth API
    try {
        const profile = await Api.auth.getProfile();
        if (profile) {
            name = profile.fullName || name;
            email = profile.email || email;
            phone = profile.phoneNumber || phone;
            age = profile.age || age;
            gender = profile.gender || gender;
            
            // Cache back to local storage
            localStorage.setItem('mediai_user_name', name);
            localStorage.setItem('mediai_user_email', email);
            localStorage.setItem('mediai_user_phone', phone);
            localStorage.setItem('mediai_user_age', age);
            localStorage.setItem('mediai_user_gender', gender);
        }
    } catch (err) {
        console.warn('[Report] Failed to fetch latest profile details, using local storage fallback:', err);
    }

    // Translate Gender dynamically
    if (lang === 'ar') {
        if (gender === 'Male' || gender === 'male' || gender === 'ذكر') {
            gender = 'ذكر';
        } else if (gender === 'Female' || gender === 'female' || gender === 'أنثى') {
            gender = 'أنثى';
        }
    } else {
        if (gender === 'Male' || gender === 'male' || gender === 'ذكر') {
            gender = 'Male';
        } else if (gender === 'Female' || gender === 'female' || gender === 'أنثى') {
            gender = 'Female';
        }
    }

    // Format Age
    if (age === '0' || age === 0 || !age || age === '—') {
        age = '—';
    } else {
        age = lang === 'ar' ? age + ' سنة' : age + ' Years';
    }

    // Populate Patient Info
    document.getElementById('reportPatientName').textContent = name;
    document.getElementById('reportPatientEmail').textContent = email;
    document.getElementById('reportPatientPhone').textContent = phone;
    document.getElementById('reportPatientAge').textContent = age;
    document.getElementById('reportPatientGender').textContent = gender;

    // Populate Reference and Date
    document.getElementById('reportRefId').textContent = refNo;
    document.getElementById('reportRefId2').textContent = refNo;

    const today = new Date();
    const locale = lang === 'ar' ? 'ar-EG' : 'en-US';
    const dateStr = today.toLocaleDateString(locale, { year: 'numeric', month: 'long', day: 'numeric' });
    const timeStr = today.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });
    const dateTimeStr = dateStr + ' | ' + timeStr;
    
    document.getElementById('reportDate').textContent = dateTimeStr;

    // Populate Scan Details (with API and wizards fallback)
    const scanType = document.getElementById('scanType').value;
    let examName = '—';
    if (scanType === 'xray_bone') {
        examName = lang === 'ar' ? 'أشعة سينية (كسور العظام)' : 'X-Ray (Bone Fracture)';
    } else if (scanType === 'ecg_heart') {
        examName = lang === 'ar' ? 'أشعة الصدر (الالتهاب الرئوي)' : 'X-Ray (Pneumonia)';
    } else if (scanType === 'brain_neurology') {
        examName = lang === 'ar' ? 'أورام المخ (الرنين المغناطيسي)' : 'Brain Tumors (MRI)';
    } else {
        const examTitleEl = document.getElementById('selectedExamTitle');
        if (examTitleEl && examTitleEl.textContent !== '...' && examTitleEl.textContent.trim()) {
            examName = examTitleEl.textContent;
        }
    }
    document.getElementById('reportScanType').textContent = examName;

    // Populate Scan Image on Page 1
    const reportImg = document.getElementById('reportScanImage');
    const imageContainer = document.getElementById('reportScanImageContainer');
    const findingsTextContainer = document.getElementById('reportFindingsTextContainer');
    
    // Choose image source: custom uploaded data url -> preview DOM image -> heatmap base64 fallback
    let scanImageSrc = window.lastUploadedFileDataUrl;
    if (!scanImageSrc) {
        const previewImg = document.querySelector('#previewMedia img');
        if (previewImg) {
            scanImageSrc = previewImg.src;
        } else if (report.heatmap) {
            scanImageSrc = "data:image/jpeg;base64," + report.heatmap;
        }
    }

    if (scanImageSrc && reportImg) {
        reportImg.src = scanImageSrc;
        reportImg.style.display = 'block';
        if (imageContainer) {
            imageContainer.style.display = 'table-cell';
            imageContainer.style.width = '';
        }
        if (findingsTextContainer) {
            findingsTextContainer.style.width = '';
        }
    } else if (reportImg) {
        reportImg.style.display = 'none';
        if (imageContainer) {
            imageContainer.style.display = 'none';
        }
        if (findingsTextContainer) {
            findingsTextContainer.style.width = '100%';
        }
    }

    // Populate Results (Page 1)
    const conditionEl = document.getElementById('detectedCondition');
    const conditionTitle = conditionEl ? conditionEl.textContent.trim() : '—';
    document.getElementById('reportResultTitle').textContent = conditionTitle;

    // Generate Dynamic Professional Summary (Page 1) to replace duplicate Title/Desc
    const findingsBox = document.querySelector('.premium-findings-box p');
    let summaryText = '';

    if (scanType === 'xray_bone') {
        const isFractured = conditionTitle.includes('مكسورة') || conditionTitle.toLowerCase().includes('fracture') || conditionTitle.toLowerCase().includes('displaced');
        if (isFractured) {
            summaryText = lang === 'ar'
                ? "قام نظام التشخيص بالذكاء الاصطناعي بتحليل صورة الأشعة السينية المرفقة، وأظهرت النتائج وجود مؤشرات واضحة لكسر في العظام. يوصى بالمتابعة العاجلة مع طبيب عظام مختص لتحديد العلاج المناسب."
                : "The AI diagnostic system analyzed the uploaded X-Ray scan and detected clear indications of a bone fracture. Immediate consultation with an orthopedic specialist is recommended.";
        } else {
            summaryText = lang === 'ar'
                ? "قام نظام التشخيص بالذكاء الاصطناعي بتحليل صورة الأشعة السينية المرفقة، وأظهرت النتائج أن بنية العظام طبيعية وسليمة تماماً ولا توجد علامات لكسور واضحة."
                : "The AI diagnostic system analyzed the uploaded X-Ray scan and found normal bone structure with no visible signs of fracture.";
        }
    } else if (scanType === 'brain_neurology') {
        const isTumor = conditionTitle.includes('ورم') || conditionTitle.toLowerCase().includes('tumor') || conditionTitle.toLowerCase().includes('mass');
        if (isTumor) {
            summaryText = lang === 'ar'
                ? "تم تحليل صور الرنين المغناطيسي للدماغ بواسطة النظام، وأظهرت النتائج وجود كتلة أو ورم دماغي مشبوه. يتطلب ذلك تقييماً طبياً عاجلاً من أخصائي جراحة المخ والأعصاب."
                : "The brain MRI scan analysis indicates the presence of a suspicious mass or brain tumor. Urgent clinical evaluation by a neurosurgeon is required.";
        } else {
            summaryText = lang === 'ar'
                ? "أظهر تحليل الرنين المغناطيسي للدماغ أن الأنسجة الدماغية طبيعية وسليمة تماماً ولا توجد علامات لوجود أورام أو كتل غير طبيعية."
                : "The brain MRI scan analysis shows normal brain tissues with no visible signs of abnormal masses or tumors.";
        }
    } else if (scanType === 'ecg_heart') {
        const isAbnormal = conditionTitle.includes('التهاب') || conditionTitle.includes('مريض') || conditionTitle.toLowerCase().includes('pneumonia') || conditionTitle.toLowerCase().includes('abnormal') || conditionTitle.toLowerCase().includes('warning');
        if (isAbnormal) {
            summaryText = lang === 'ar'
                ? "قام نظام التشخيص بالذكاء الاصطناعي بتحليل صورة أشعة الصدر المرفقة، وأظهرت النتائج وجود مؤشرات واضحة للالتهاب الرئوي. يوصى بمراجعة عاجلة لطبيب الأمراض الصدرية والجهاز التنفسي."
                : "The AI diagnostic system analyzed the uploaded chest X-Ray and detected clear indications of pneumonia. Clinical review with a pulmonologist is recommended.";
        } else {
            summaryText = lang === 'ar'
                ? "أظهر تحليل أشعة الصدر المرفقة سلامة الرئتين وخلوهما تماماً من علامات الالتهاب الرئوي أو أي ارتشاحات رئوية غير طبيعية."
                : "The chest X-Ray scan analysis indicates healthy lungs with no visible signs of pneumonia or abnormal infiltrates.";
        }
    } else {
        summaryText = findingsBox ? findingsBox.textContent.trim() : conditionTitle;
    }

    document.getElementById('reportResultDesc').textContent = summaryText;

    const confEl = document.getElementById('confidenceLevel');
    document.getElementById('reportConfidence').textContent = confEl ? confEl.textContent : '—';

    const recEl = document.getElementById('recommendedSpecialist');
    document.getElementById('reportRecommendation').textContent = recEl ? recEl.textContent.trim() : '—';

    // Populate Detailed Report (Page 2) Static Fields
    const page2 = document.querySelector('#medicalPrintReport .page-2');

    // Helper to set text and toggle visibility
    const setTextAndToggle = (elId, boxId, text) => {
        const el = document.getElementById(elId);
        const box = document.getElementById(boxId);
        if (el && box) {
            if (text && text.trim() && text !== '—') {
                el.textContent = text;
                box.classList.remove('d-none');
            } else {
                box.classList.add('d-none');
            }
        }
    };

    setTextAndToggle('rptBoneName', 'rptBoneNameBox', report.boneName);
    setTextAndToggle('rptFractureType', 'rptFractureTypeBox', report.fractureType);
    setTextAndToggle('rptSeverity', 'rptSeverityBox', report.severity);
    setTextAndToggle('rptMedicalReport', 'rptMedicalReportBox', report.medicalReport);
    setTextAndToggle('rptTreatmentPlan', 'rptTreatmentPlanBox', report.treatmentPlan);

    // Set custom icon and label dynamically for print page 2
    const affectedBoneLabelEl = document.querySelector('#rptBoneNameBox .rpt-tech-label');
    const affectedBoneValueEl = document.querySelector('#rptBoneNameBox .rpt-tech-value i');
    if (affectedBoneLabelEl && affectedBoneValueEl) {
        if (scanType === 'brain_neurology') {
            affectedBoneLabelEl.textContent = lang === 'ar' ? 'البنية التشريحية المتأثرة' : 'Affected Anatomy';
            affectedBoneValueEl.className = 'fa-solid fa-brain text-primary me-2';
        } else {
            affectedBoneLabelEl.textContent = lang === 'ar' ? 'العظمة المتأثرة' : 'Affected Bone';
            affectedBoneValueEl.className = 'fa-solid fa-bone text-primary me-2';
        }
    }

    // Style Page 2 Severity Dot & Box
    const severityDot = document.getElementById('rptSeverityDot');
    const severityBox = document.getElementById('rptSeverityBox');
    if (severityDot && report.severity) {
        let dotColor = "#ffc107"; // default warning yellow
        let bgColor = "#fff3cd";
        let textColor = "#856404";
        
        const sev = report.severity.toLowerCase();
        if (sev.includes("شديد") || sev.includes("high") || sev.includes("severe") || sev.includes("critical") || sev.includes("حرج") || sev.includes("خطورة")) {
            dotColor = "#dc3545"; // critical red
            bgColor = "#f8d7da";
            textColor = "#721c24";
        } else if (sev.includes("طبيعي") || sev.includes("low") || sev.includes("mild") || sev.includes("normal") || sev.includes("سليم")) {
            dotColor = "#198754"; // normal green
            bgColor = "#d1e7dd";
            textColor = "#0f5132";
        }
        
        severityDot.style.backgroundColor = dotColor;
        if (severityBox) {
            severityBox.style.backgroundColor = bgColor;
            severityBox.style.color = textColor;
            severityBox.style.borderColor = dotColor;
        }
    }

    // Heatmap Image on Page 2
    const heatmapBox = document.getElementById('rptHeatmapBox');
    const heatmapImg = document.getElementById('rptHeatmapImage');
    const textCol = document.querySelector('.rpt-details-text');
    if (heatmapBox && heatmapImg) {
        if (report.heatmap) {
            heatmapImg.src = "data:image/jpeg;base64," + report.heatmap;
            heatmapBox.classList.remove('d-none');
            if (textCol) textCol.style.width = '60%';
        } else {
            heatmapBox.classList.add('d-none');
            if (textCol) textCol.style.width = '100%';
        }
    }

    if (page2) {
        page2.style.display = 'flex';
    }

    // Trigger Print
    window.print();

    // If opened as a popup from the dashboard, close after printing
    if (new URLSearchParams(window.location.search).get('popup') === '1') {
        window.close();
    }
};
